import type {
  AdminExamItem,
  ExamRecordItem,
  ExamStudentItem,
  PaperItem,
  QuestionBankItem,
  QuestionTypeItem,
  ScoreSummaryItem,
} from './types'

export const examStudentFixtures: ExamStudentItem[] = [
  {
    id: 'exam-001',
    title: '第一阶段软件工程测验',
    topicLabel: '需求分析专题',
    teacher: '王老师',
    status: 'ready',
    schedule: '今天 19:30 - 20:30',
    duration: '60 分钟',
    questionCount: 4,
    summary: '覆盖需求分析、用例建模、架构分层和质量属性四个重点知识点。',
    tags: ['阶段测验', '闭卷', '限时'],
    questionBankNote: '本场测验从“需求分析共享题库”中组题，同一题库也用于作业抽题与课堂练习。',
    rules: [
      { label: '进入规则', content: '请在开始前确认网络与浏览器环境，进入后系统将按倒计时记录进度。' },
      { label: '答题要求', content: '单选与多选题自动判分，简答题按摘要长度与关键词完整度进行示意评分。' },
      { label: '提交说明', content: '提交后可立即查看成绩摘要，教师端会在结果汇总页同步成绩变化。' },
    ],
    readyChecklist: ['确认姓名与主题信息', '确保 60 分钟内可连续作答', '先浏览题目结构，再开始正式答题'],
    questions: [
      {
        id: 'q-001',
        title: '单选题 1',
        prompt: '在分层架构中，最适合承载业务规则聚合与流程协调的是哪一层？',
        kind: 'single',
        score: 20,
        options: [
          { key: 'a', label: '表现层' },
          { key: 'b', label: '服务层' },
          { key: 'c', label: '数据源层' },
          { key: 'd', label: '工具层' },
        ],
        correctAnswer: 'b',
        answerTip: '关注系统职责分配，而不是技术组件名称。',
      },
      {
        id: 'q-002',
        title: '多选题 1',
        prompt: '以下哪些内容属于题库资产在作业与考试之间共享的直接收益？',
        kind: 'multiple',
        score: 20,
        options: [
          { key: 'a', label: '题目复用' },
          { key: 'b', label: '评分口径统一' },
          { key: 'c', label: '减少页面数量' },
          { key: 'd', label: '降低出题重复劳动' },
        ],
        correctAnswer: ['a', 'b', 'd'],
        answerTip: '可从教学运营效率和资产沉淀两个角度思考。',
      },
      {
        id: 'q-003',
        title: '单选题 2',
        prompt: '学生端考试流程中，进入确认页的主要价值是什么？',
        kind: 'single',
        score: 20,
        options: [
          { key: 'a', label: '替代考试列表' },
          { key: 'b', label: '承接规则确认与开始动作' },
          { key: 'c', label: '直接展示教师统计报表' },
          { key: 'd', label: '替代答题页' },
        ],
        correctAnswer: 'b',
        answerTip: '思考确认页在流程中的承上启下作用。',
      },
      {
        id: 'q-004',
        title: '简答题 1',
        prompt: '请简要说明为什么题库管理入口仍建议放在 exam 模块，而不是放到 homework 模块。',
        kind: 'short',
        score: 40,
        correctAnswer: 'shared-bank-kept-in-exam',
        answerTip: '可以围绕“共享资产”“模块所有权”“考试主场景”三个关键词组织答案。',
      },
    ],
    answerDraft: {
      'q-001': '',
      'q-002': [],
      'q-003': '',
      'q-004': '',
    },
    result: {
      score: '待提交',
      rankHint: '结果将在提交后生成',
      submittedAt: '未提交',
      durationUsed: '--',
      feedback: '开始考试后系统会根据当前答题情况生成结果摘要。',
      highlights: ['当前题库与作业共享', '正式提交后同步到教师成绩视图'],
    },
  },
  {
    id: 'exam-002',
    title: 'Web 前端阶段测验',
    topicLabel: '界面实现专题',
    teacher: '周老师',
    status: 'upcoming',
    schedule: '周五 18:30 - 19:15',
    duration: '45 分钟',
    questionCount: 3,
    summary: '围绕组件拆分、状态管理和路由设计三个主题组织的阶段测验。',
    tags: ['即将开放', '阶段测验'],
    questionBankNote: '本场测验会从前端开发共享题库中抽题，部分题目也会在课堂作业中复用。',
    rules: [{ label: '开放状态', content: '考试将在周五统一开放，开放前仅可查看说明与范围。' }],
    readyChecklist: ['提前完成实验预习', '检查资料中的重点提醒'],
    questions: [],
    answerDraft: {},
    result: {
      score: '未开放',
      rankHint: '开放后可进入',
      submittedAt: '--',
      durationUsed: '--',
      feedback: '请在开放时间内进入确认页开始作答。',
      highlights: ['考试尚未开放'],
    },
  },
  {
    id: 'exam-003',
    title: '系统设计综合测验',
    topicLabel: '系统设计专题',
    teacher: '李老师',
    status: 'completed',
    schedule: '已于上周完成',
    duration: '50 分钟',
    questionCount: 4,
    summary: '已完成提交，可查看得分、作答摘要与后续复盘建议。',
    tags: ['已完成', '可复盘'],
    questionBankNote: '本次试卷来自系统设计综合题库，该题库同样支持作业复用与课堂测验。',
    rules: [{ label: '复盘建议', content: '重点查看系统边界和状态流相关题目的错误原因。' }],
    readyChecklist: ['已完成本场作答'],
    questions: [],
    answerDraft: {},
    result: {
      score: '91 / 100',
      rankHint: '班级前 12%',
      submittedAt: '上周三 20:18',
      durationUsed: '42 分钟',
      feedback: '整体表现稳定，建议继续巩固模块边界与事件协作的答题表达。',
      highlights: ['模块边界题全部正确', '简答题表达完整度较高'],
    },
  },
]

export const questionBankFixtures: QuestionBankItem[] = [
  {
    id: 'bank-001',
    name: '需求分析共享题库',
    questionCount: 128,
    sharedUsage: '服务需求分析作业、阶段测验与课堂练习',
    owner: '软件工程教研组',
    updatedAt: '2026-04-12 18:10',
    description: '沉淀需求分析、架构分层、质量属性和项目过程控制相关题目。',
    tags: ['共享题库', '作业复用', '考试复用'],
  },
  {
    id: 'bank-002',
    name: '界面实现共享题库',
    questionCount: 96,
    sharedUsage: '支撑界面实现作业抽题、实验复盘问答和阶段测验',
    owner: '前端教研组',
    updatedAt: '2026-04-11 11:40',
    description: '覆盖组件拆分、状态管理、路由设计和页面性能优化。',
    tags: ['前端', '共享资产'],
  },
  {
    id: 'bank-003',
    name: '系统设计综合题库',
    questionCount: 74,
    sharedUsage: '用于综合作业和期末前模拟测验',
    owner: '系统设计教研组',
    updatedAt: '2026-04-09 16:20',
    description: '聚焦系统边界、协作流程和技术选型判断。',
    tags: ['系统设计', '综合训练'],
  },
]

export const questionTypeFixtures: QuestionTypeItem[] = [
  { id: 'type-001', name: '单选题', questionCount: 132, usage: '课堂测验 / 阶段考试', summary: '适合基础知识点判定与概念辨析。' },
  { id: 'type-002', name: '多选题', questionCount: 64, usage: '作业抽题 / 阶段考试', summary: '适合检验模块关系、收益与风险的组合判断。' },
  { id: 'type-003', name: '简答题', questionCount: 48, usage: '作业 / 实验复盘 / 考试', summary: '适合考察结构化表达和设计推理。' },
]

export const paperFixtures: PaperItem[] = [
  {
    id: 'paper-001',
    title: '软件工程阶段测验卷 A',
    topicLabel: '需求分析专题',
    questionCount: 12,
    duration: '60 分钟',
    status: 'used',
    questionBankName: '需求分析共享题库',
    updatedAt: '2026-04-12 18:30',
    summary: '围绕需求、架构与质量属性组织的标准阶段测验卷。',
    tags: ['已使用', '阶段测验'],
  },
  {
    id: 'paper-002',
    title: '前端开发能力测验卷 B',
    topicLabel: '界面实现专题',
    questionCount: 10,
    duration: '45 分钟',
    status: 'ready',
    questionBankName: '界面实现共享题库',
    updatedAt: '2026-04-11 10:25',
    summary: '适合本周课堂测验与课后复盘。',
    tags: ['待发布', '共享题库'],
  },
]

export const adminExamFixtures: AdminExamItem[] = [
  {
    id: 'exam-001',
    title: '第一阶段软件工程测验',
    topicLabel: '需求分析专题',
    status: 'running',
    scope: '软工 2401 / 2402',
    schedule: '今天 19:30 - 20:30',
    paperTitle: '软件工程阶段测验卷 A',
    candidateCount: 86,
    submittedCount: 61,
    averageScore: '84.6',
    summary: '当前测验正在进行，需重点关注未提交人数与异常记录。',
    tags: ['进行中', '共享题库'],
  },
  {
    id: 'exam-002',
    title: 'Web 前端阶段测验',
    topicLabel: '界面实现专题',
    status: 'scheduled',
    scope: '前端 2401',
    schedule: '周五 18:30 - 19:15',
    paperTitle: '前端开发能力测验卷 B',
    candidateCount: 42,
    submittedCount: 0,
    averageScore: '--',
    summary: '待开放的周内测验，可在开放前继续调整题库与试卷。',
    tags: ['待开始'],
  },
  {
    id: 'exam-003',
    title: '系统设计综合测验',
    topicLabel: '系统设计专题',
    status: 'closed',
    scope: '系统设计 2401',
    schedule: '上周三 19:00 - 19:50',
    paperTitle: '系统设计综合卷',
    candidateCount: 39,
    submittedCount: 39,
    averageScore: '88.9',
    summary: '已完成结课前综合测验，当前主要关注成绩汇总与错题复盘。',
    tags: ['已结束', '可复盘'],
  },
]

export const examRecordFixtures: ExamRecordItem[] = [
  { id: 'record-001', examId: 'exam-001', studentName: '李明', className: '软工 2402', status: 'in_progress', startedAt: '今天 19:33', risk: 'medium', note: '已进入考试，尚未提交。' },
  { id: 'record-002', examId: 'exam-001', studentName: '陈晨', className: '软工 2401', status: 'submitted', startedAt: '今天 19:31', submittedAt: '今天 20:05', score: '87', risk: 'low', note: '答题完整，待统一汇总。' },
  { id: 'record-003', examId: 'exam-001', studentName: '王悦', className: '软工 2401', status: 'not_started', startedAt: '--', risk: 'high', note: '尚未进入考试，需关注提醒。' },
  { id: 'record-004', examId: 'exam-003', studentName: '李明', className: '系统设计 2401', status: 'reviewed', startedAt: '上周三 19:02', submittedAt: '上周三 19:44', score: '91', risk: 'low', note: '已完成复盘建议。' },
]

export const scoreSummaryFixtures: ScoreSummaryItem[] = [
  { label: '平均分', value: '84.6', detail: '进行中考试的实时平均分。', tone: 'primary' },
  { label: '优秀率', value: '31%', detail: '90 分及以上占比。', tone: 'success' },
  { label: '预警人数', value: '5', detail: '未开始或长时间停留在进行中。', tone: 'warning' },
  { label: '共享题库复用率', value: '78%', detail: '作业与考试共用题目的近期复用情况。', tone: 'accent' },
]
